.ORG 0
	SJMP INIT
.org 23h
	SJMP SERIAL
.ORG 30h
INIT:
	MOV TMOD, #0x20
	MOV TL1, #245
	MOV TH1, #245
	MOV SCON, #0x50
	SETB TR1
	MOV IE, #0x90
	SJMP $
SERIAL:
	PUSH A
	JNB TI, RECEIVED
	CLR TI
	SJMP END_SERIAL_INTERRUPT
RECEIVED:
	MOV A, SBUF
	CLR RI
	CJNE A, #0x5a, NOT_Z
	SJMP SEND_LETTER
NOT_Z:	JNC END_SERIAL_INTERRUPT	; >= 'Z'
	CJNE A, #0x41, NEXT
NEXT:	JNC SEND_LETTER ; >= 'A'
	SJMP END_SERIAL_INTERRUPT
SEND_LETTER:
	MOV SBUF, A
END_SERIAL_INTERRUPT:
	POP A
	RETI
